### ISSUE TITLE
Demo/Samples not working

### ISSUE THREAD

**Issue by rink151** [c17r/jAutoCalc#14]
I downloaded all files and added them to my HTDOCS folder and copy-pasted index page from ReadMe but for some reason, the calculation is not working. What I am doing wrong. Please advise.

Here is by page code:

 <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/c17r/jautocalc/dist/jautocalc.min.js"></script>
    <script type="text/javascript">

    	$(function() {
    		$('form[name=cart] tr[name=line_items]').jAutoCalc({keyEventsFire: true, decimalPlaces: 2});
    		$('form[name=cart]').jAutoCalc({decimalPlaces: 2});

    	});

    </script>
    <form name="cart">
    <table>
        <tr>
            <th>Item</th>
            <th>Qty</th>
            <th>Price</th>
            <th>&nbsp;</th>
            <th>Item Total</th>
        </tr>
        <tr>
            <td>Stuff</td>
            <td><input type="text" name="qty" value="1"></td>
            <td><input type="text" name="price" value="9.99"></td>
            <td>&nbsp;</td>
            <td><input type="text" name="item_total" value="" jAutoCalc="{qty} * {price}"></td>
        </tr>
        <tr>
            <td>More Stuff</td>
            <td><input type="text" name="qty" value="2"></td>
            <td><input type="text" name="price" value="12.50"></td>
            <td>&nbsp;</td>
            <td><input type="text" name="item_total" value="" jAutoCalc="{qty} * {price}"></td>
        </tr>
        <tr>
            <td>And More Stuff</td>
            <td><input type="text" name="qty" value="3"></td>
            <td><input type="text" name="price" value="99.99"></td>
            <td>&nbsp;</td>
            <td><input type="text" name="item_total" value="" jAutoCalc="{qty} * {price}"></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
            <td>Subtotal</td>
            <td>&nbsp;</td>
            <td><input type="text" name="sub_total" value="" jAutoCalc="SUM({item_total})"></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
            <td>
                Tax:
                <select name="tax">
                    <option value=".06">CT Tax</option>
                    <option value=".00">Tax Free</option>
                </select>
            </td>
            <td>&nbsp;</td>
            <td><input type="text" name="tax_total" value="" jAutoCalc="{sub_total} * {tax}"></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
            <td>Total</td>
            <td>&nbsp;</td>
            <td><input type="text" name="grand_total" value="" jAutoCalc="{sub_total} + {tax_total}"></td>
        </tr>
    </table>
</form>

![image](https://user-images.githubusercontent.com/77497459/112181940-3cd6c300-8bd3-11eb-9187-3ebf9570c475.png)

**Comment by c17r** [comment]
I was cleaning up the html/javascript in the readme example and the demo ... and ended up breaking them. Nothing wrong with the library code itself.

I have updated both the README and http://c17r.github.io/jAutoCalc/sample.html so they now work

**Comment by rink151** [comment]
Thank you so much. Its working now. 
Great help with my School project
