### ISSUE TITLE
I want to collect the selected items

### ISSUE THREAD

**Issue by nFnK** [c17r/jAutoCalc#2]
Hello,
I want to collect the checked (checkbox) items. How can I do?
thanks.
  input id="checkbox1" name="urununkodu" value="ura-12409" type="checkbox" checked 
 input id="checkbox2" name="urununkodu" value="ura-133" type="checkbox" 
`http://c17r.github.io/jAutoCalc/sample.html`
<tr name="line_items">

<td>  <input id="checkbox1" name="urununkodu" value="ura-12409" type="checkbox" checked ></td>
					<td><button name="remove">Remove</button></td>
					<td>Stuff</td>
					<td><input type="text" name="qty" value="1"></td>
					<td><input type="text" name="price" value="9.99"></td>
					<td>&nbsp;</td>
					<td><input type="text" name="item_total" value="" jAutoCalc="{qty} * {price}"></td>
				</tr>
				<tr name="line_items">
<td>  <input id="checkbox2" name="urununkodu" value="ura-133" type="checkbox" ></td>
					<td><button name="remove">Remove</button></td>
					<td>More Stuff</td>
					<td><input type="text" name="qty" value="2"></td>
					<td><input type="text" name="price" value="12.50"></td>
					<td>&nbsp;</td>
					<td><input type="text" name="item_total" value="" jAutoCalc="{qty} * {price}"></td>
				</tr>``

**Comment by c17r** [comment]
If you are asking how in jQuery, to find all the checkbox items that are checked, that's not really germane to this plugin but the answer is `$('input:checkbox:checked')` will give you an array of all checked checkboxes.

If you are asking how to use checkboxes with jAutoCalc, they don't really work since the `val()` of a checkbox doesn't change based on whether it's checked or not.  We could check to see if the element is a checkbox AND if it's checked, but what would we do if it's not checked?

**Comment by nFnK** [comment]
I want like this  : https://i.imgur.com/ABzhsXk.jpg
how can I add "input:checkbox:checked" to this code : 
    $('form[name=cart]').jAutoCalc('destroy');
       $('form[name=cart] tr[name=line_items] input:checkbox:checked').jAutoCalc({keyEventsFire: true, decimalPlaces: 2, emptyAsZero: true});
          $('form[name=cart]').jAutoCalc({decimalPlaces: 2});

**Comment by c17r** [comment]
I don't understand how the checkboxes would be used in a calculation done by this library

**Comment by nFnK** [comment]
I would like to collect only selected checkbox items.  first time every checkboxs is checked.
if I click some checkbox and it will empty. then selected checkbox items will collect 

it is like this picture  https://i.imgur.com/ABzhsXk.jpg
`
    $(document).ready(function() {
$('#gizlenigoster').hide();
      function autoCalcSetup() {
          $('form[name=cart]').jAutoCalc({decimalPlaces: 2});
      }
      autoCalcSetup();


    $(document).on("click", ".delete", function( e ) {
        e.preventDefault();

        var form = $(this).parents('form')
        $(this).parents('tr').remove();
        autoCalcSetup();

      $('#gizlenigoster').fadeIn('slow');



            var cart_item = 0;
            var id = $(this).attr("id");
            var dataString = 'id='+ id ;
            var parent = $(this).parent();

            $.ajax({
            type: "POST",
            url: "{{ URL }}{{ dil }}/cart/cartdelete",
            data: dataString,
            cache: false,


            }).done(function(data){ //on Ajax success
              $("#gizlenigoster").delay(3000).fadeOut();

            });

      });

      $('button[name=add]').click(function(e) {
        e.preventDefault();

        var $table = $(this).parents('table');
        var $top = $table.find('tr[name=line_items]').first();
        var $new = $top.clone(true);

        $new.jAutoCalc('destroy');
        $new.insertBefore($top);
        $new.find('input[type=text]').val('');
        autoCalcSetup();

      });

    });
`

**Comment by c17r** [comment]
By "collecting" you mean sending to the server-side?  That is beyond the scope of this library.

**Comment by nFnK** [comment]
no. I said you before what do I want. 
you will understand better when you looked this url
https://i.imgur.com/uG7vJ1u.jpg

**Comment by c17r** [comment]
There is no logic control in the library.  It doesn't support "if" "for" "while" or things like that.  Just basic math.  It might be possible as a future enhancement, like `jsCalc='{IF(<truthy statement>, {qty} * {price}, 0)}'`.  Feel free to open a PR if you write something up yourself and I'll take a look.

**Comment by nFnK** [comment]
I don't know so much js until I will make a development. But  thanks for your help
