### ISSUE TITLE
How to add Rows and Delete Rows to calculate again?

### ISSUE THREAD

**Issue by aayadao** [c17r/jAutoCalc#20]
I have a problem in adding and removing rows. When I type numbers to calculate it using jAutoCalc library, it's working. So I don't have any problem with that. But when I want to add some rows and removing some rows, it shows nothing. And I don't see anything error in my program. But according to Inspects in my Browser (I'm using Microsoft Edge), I have an error in "$new.jAutoCalc('destroy'); " and it says that "$new.jAutoCalc" is not a function. 

I use this following codes:

HTML:
                      <div class="container">
                        <form name="transactions">
                          <table class="table table-hover table-bordered table-striped" name="transactions">
                            <thead>
                              <tr>
                                <th></th>
                                <th>Item</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                <th>Item Total</th>
                              </tr>        
                            </thead>
                            <tbody>
                              <tr name="services">
                                <td><button class="btn btn-primary" name="remove">Remove</button></td>
                                <td>Stuff</td>
                                <td><input type="text" class="form-control" name="qty" value="3"></td>
                                <td><input type="text" class="form-control" name="price" value="12"></td>
                                <td><input type="text" class="form-control" name="item_total" jAutoCalc="{qty} * {price}"></td>
                              </tr>
                              <tr>
                                <td colspan="2">&nbsp;</td>
                                <td>Subtotal</td>
                                <td>&nbsp;</td>
                                <td><input type="text" class="form-control" name="subtotal" jAutoCalc="SUM({item_total})"></td>
                              </tr>
                              <tr>
                                <td colspan="2"></td>
                                <td>Tax</td>
                                <td>
                                  <select class="form-control" name="tax">
                                    <option value=".06">CT Tax</option>
                                    <option value=".00">Tax Free</option>
                                  </select>
                                </td>
                                <td><input type="text" class="form-control" name="tax_total" jAutoCalc="{subtotal} * {tax}"></td>
                              </tr>
                              <tr>
                                <td colspan="2"></td>
                                <td>Total</td>
                                <td>&nbsp;</td>
                                <td><input type="text" class="form-control" name="grand_total" jAutoCalc="{subtotal} + {tax_total}"></td>
                              </tr>
                              <tr>
                                <td colspan="4"></td>
                                <td><button class="btn btn-primary" name="add">Add Row</button></td>
                              </tr>
                            </tbody>
                          </table>
                        </form>
                      </div>
                      
----------------------------------------
 JS:
 
function autoCalcSetup(){
    $('form[name=transactions]').jAutoCalc('destroy');
    $('form[name=transactions] tr[name=services]').jAutoCalc({keyEventsFire: true, decimalPlaces: 2, emptyAsZero: true});
    $('form[name=transactions]').jAutoCalc({decimalPlaces: 2});
}

autoCalcSetup();

$('button[name=remove]').click(function(e){
    e.preventDefault();

    var form = $(this).parents('form')

    $(this).parents('tr').remove();
    autoCalcSetup();
});

$('button[name=add]').click(function(e){
    e.preventDefault();

    var $table = $(this).parents('table');
    var $top = $table.find('tr[name=services]').first();
    var $new = $top.clone(true);
    
    $new.jAutoCalc('destroy');             //this is my error. According to Inspects in Browser
    $new.insertBefore($top);
    $new.find('input[type=text]').val('');

    autoCalcSetup();
});

-------------------------------------

I hope you can help me with this problem. I need to do this for our Capstone Project. Thank so much! Godbless you! :D

**Comment by c17r** [comment]
I can't really debug because you didn't include the full code. Either attach the full html/js or make an example using a site like codesandbox, codepen, jsfiddle, stackblitz, etc.

My only guess is, are you sure you are included both jQuery and the jAutoCalc libraries?

**Comment by aayadao** [comment]
@c17r Yes, I'm pretty sure that I included both jQuery and jAutoCalc libraries. Because I have no problem in computing numbers dynamically. I have problem in adding Rows and to Removing Rows.

Here's my full code. I'm sorry for not including it. :D

[Full Codes.zip](https://github.com/c17r/jAutoCalc/files/6873482/Full.Codes.zip)

**Comment by c17r** [comment]
[working.zip](https://github.com/c17r/jAutoCalc/files/6878152/working.zip)

I took your zip and:
1. unpacked it
2. edited transaction.php to remove all the script/link assets that aren't relevant
3. edited the three remaining script tags to be relevant paths
4. renamed transaction.php to index.html
5. in the command line, `cd`ed into the directory directory with index.html and ran `python -m http.server`
6. in the browser, navigated to `http://localhost:8000`

and everything worked fine, `Add Row` and `Remove` are working just fine as are all the calculations. See the attached zip file.

It's possible another library you are using is causing a load time conflict. Looking at your transaction.js file, it's recommended to have any jQuery dependent code be wrapped in a `$(function() {}` block to make sure it doesn't fire before everything is loaded (see https://learn.jquery.com/using-jquery-core/document-ready/). You have so many script/link tags that your transaction.js could be executing before one of both of jQuery and jAutoCalc are downloaded and executed.
