### ISSUE TITLE
how to do calcultions for multiple tables

### ISSUE THREAD

**Issue by Mahmood-Hussain** [c17r/jAutoCalc#3]
I'm trying to use the plugin for multiple tables within the same form. The problem is that it does calculations for the second table also but doesn't accept the true value for keyEventsFire.

the code is here:

                     function autoCalcSetup() {
                        $('form[name=cart]').jAutoCalc('destroy');
                        $('form[name=cart] tr[name=line_items], form[name=cart] 
                             tr[name=payment_milestones]').jAutoCalc({
                            keyEventsFire: true,
                            decimalPlaces: 2,
                            emptyAsZero: true
                        });
                        $('form[name=cart]').jAutoCalc({
                            decimalPlaces: 2
                        });
                    }
                    autoCalcSetup();
                    
                    $('button[name=remove]').click(function(e) {
                        e.preventDefault();

                        var form = $(this).parents('form')
                        $(this).parents('tr').remove();
                        autoCalcSetup();
                    });

                    $('button[name=add]').click(function(e) {
                        e.preventDefault();

                        var $table = $(this).parents('table');
                        var $bottom = $table.find('tr[name=line_items], tr[name=payment_milestones]').last();
                        var $new = $bottom.clone(true);

                        $new.jAutoCalc('destroy');
                        $new.insertAfter($bottom);
                        $new.find('input[type=text]').val('');
                        $new.find('button[name=remove]').attr('disabled', false);
                        autoCalcSetup();
                    });
                });

it doesn't accept keyEventsFire it only works for Focus

**Comment by c17r** [comment]
The JS snippet you provided works fine for me.  If you provide both the JS and HTML of an example that doesn't work I'll be happy to take a look.

**Comment by c17r** [comment]
Closing due to no follow up
