### ISSUE TITLE
Parsing error: unrecognised value

### ISSUE THREAD

**Issue by icex** [c17r/jAutoCalc#6]
On: https://www.jqueryscript.net/demo/Do-Calculations-Form-Fields-AutoCalc/
Just enter in Stuff -> Qty "-" instead of a number. Input fields should be validate :)

**Comment by stanj98** [comment]
Hi, I'm facing the same issue, did you find a fix?
I want to accept negative numbers but how can I do this?

**Comment by c17r** [comment]
@stanj98 I'll take a look to see if there is a better way moving forward but to deal with it today, set the `showParseError` option to false. It'll just return null and the downstream calculations will stop.

**Comment by c17r** [comment]
I just push 1.3.1 to npm that tries to parse after cleaning and stops the process if the value isn't valid.
