### ISSUE TITLE
IE11 Problem: "const" must be initialized

### ISSUE THREAD

**Issue by graftec** [c17r/jAutoCalc#8]
Hi,

Some users are complaining that jautocalc does not work with IE11.
By looking the error in javascript console, I see following:

**SCRIPT1053: "const" must be initialized.**
**jautocalc.js (198,21)**

Have you already heard about this problem?
Thx for your help.
Regards,
Alain

**Comment by c17r** [comment]
I know this issue is 9 months old but I uploaded a new version to npm that should fix it.
